name: Generate documentation

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set git user
        run: git config --global user.email "musicofbyte@gmail.com"
      - name: set git name
        run: git config --global user.name "Tochi Bedford"
      - name: Checkout documentation branch
        run: git checkout -b documentation
      - name: Pull from master branch
        run: git pull origin master
      - name: Install dependencies
        run: npm install
      - name: Generate documentation
        run: npx typedoc ./src
      - name: Add documentation files
        run: git add docs
      - name: Commit documentation
        run: git commit -m "Generate documentation"
      - name: Push documentation to branch
        run: git push origin documentation
