name: Generate documentation

on:
  push:
    branches:
      - master

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set git user
        run: git config --global user.email "musicofbyte@gmail.com"
      - name: set git name
        run: | 
          git config --global user.name "Tochi Bedford"
          git config --global --add safe.directory /github/workspace
      - name: Checkout documentation branch
        run: git checkout -b documentation
      - name: Install dependencies
        run: npm install
      - name: Generate documentation
        run: npx typedoc ./src
      - name: Add documentation files
        run: git add docs
      - name: Commit documentation
        run: git commit -m "Generate documentation"
      - name: Force push documentation to branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: documentation
          force: true
